# Generated by Django 5.2.13 on 2026-04-15 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('matricula_funcional', models.CharField(max_length=30, unique=True)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agentes_escolares',
            },
        ),
        migrations.CreateModel(
            name='CalculoModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_ativa', models.IntegerField()),
                ('data_calculo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'calculos_modulo',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('abreviacao', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'modalidades',
            },
        ),
        migrations.CreateModel(
            name='PeriodoProcessamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'periodos_processamento',
            },
        ),
        migrations.CreateModel(
            name='CalculoQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('calculo_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.calculomodulo')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cargo')),
            ],
            options={
                'db_table': 'calculo_quantidades',
            },
        ),
        migrations.CreateModel(
            name='Designacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_designacao', models.DateField()),
                ('status_designacao', models.PositiveSmallIntegerField(default=0)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.agenteescolar')),
                ('calculo_modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.calculomodulo')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cargo')),
            ],
            options={
                'db_table': 'designacoes',
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inep', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('numero_turnos', models.PositiveSmallIntegerField(default=1)),
                ('tipo_merenda', models.PositiveSmallIntegerField(default=0)),
                ('tipo_limpeza', models.PositiveSmallIntegerField(default=0)),
                ('professores_dedicados', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_calculo_modulo', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'escolas',
                'indexes': [models.Index(fields=['ultimo_calculo_modulo'], name='idx_ultimo_calculo')],
            },
        ),
        migrations.AddField(
            model_name='calculomodulo',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.escola'),
        ),
        migrations.AddField(
            model_name='calculomodulo',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.periodoprocessamento'),
        ),
        migrations.CreateModel(
            name='ContratacaoTerceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField()),
                ('situacao', models.PositiveSmallIntegerField(default=1)),
                ('calculo_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.calculomodulo')),
            ],
            options={
                'db_table': 'contratacoes_terceiros',
                'constraints': [models.UniqueConstraint(fields=('calculo_modulo', 'tipo'), name='uk_contratacao')],
            },
        ),
        migrations.CreateModel(
            name='EscolaModalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.escola')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.modalidade')),
            ],
            options={
                'db_table': 'escola_modalidades',
                'constraints': [models.UniqueConstraint(fields=('escola', 'modalidade'), name='uk_escola_modalidade')],
            },
        ),
        migrations.AddConstraint(
            model_name='calculomodulo',
            constraint=models.UniqueConstraint(fields=('escola', 'periodo'), name='uk_escola_periodo'),
        ),
    ]
