# Generated by Django 5.2.13 on 2026-04-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenteescolar',
            options={'verbose_name': 'Agente escolar', 'verbose_name_plural': 'Agentes escolares'},
        ),
        migrations.AlterField(
            model_name='agenteescolar',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inativo'), (1, 'Ativo'), (2, 'Licença')], default=1),
        ),
    ]
