# Generated by Django 5.2.13 on 2026-04-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_populate_cargos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodoprocessamento",
            name="ativo",
        ),
    ]
