# Generated by Django 5.2 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_calculomodulo_uk_escola_periodo"),
    ]

    operations = [
        migrations.AddField(
            model_name="escola",
            name="matricula_cel",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escola",
            name="pei_nove_horas",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="escola",
            name="pei_turno_diverso_tempo_parcial",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
