# Generated by Django 5.2 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_escola_pei_matricula_cel"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculomodulo",
            name="matricula_cel",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="calculomodulo",
            name="professores_dedicados",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.RemoveField(
            model_name="escola",
            name="matricula_cel",
        ),
        migrations.RemoveField(
            model_name="escola",
            name="professores_dedicados",
        ),
    ]
