# Generated by Django 5.2.13 on 2026-04-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_move_prof_matricula_cel_to_calculo_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculomodulo',
            name='status_designacao',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pendente'), (1, 'Em andamento'), (2, 'Concluído')], default=0, verbose_name='Status da Designação'),
        ),
    ]
