# Generated by Django 5.2 on 2026-04-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_calculomodulo_status_designacao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="designacao",
            old_name="status_designacao",
            new_name="status",
        ),
    ]
