# Generated by Django 5.2

from django.db import migrations, models


def _backfill_ultimo_calculo(apps, schema_editor):
    CalculoModulo = apps.get_model("app", "CalculoModulo")
    pares = (
        CalculoModulo.objects.values_list("escola_id", "periodo_id")
        .order_by("escola_id", "periodo_id")
        .distinct()
    )
    for escola_id, periodo_id in pares:
        qs = CalculoModulo.objects.filter(
            escola_id=escola_id, periodo_id=periodo_id
        ).order_by("-data_calculo", "-pk")
        ultimo_calculo_id = qs.values_list("pk", flat=True).first()
        CalculoModulo.objects.filter(escola_id=escola_id, periodo_id=periodo_id).update(
            ultimo_calculo=False
        )
        if ultimo_calculo_id is not None:
            CalculoModulo.objects.filter(pk=ultimo_calculo_id).update(ultimo_calculo=True)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_rename_designacao_status_designacao_designacao_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculomodulo",
            name="ultimo_calculo",
            field=models.BooleanField(
                default=False, verbose_name="Último Cálculo"
            ),
        ),
        migrations.RunPython(_backfill_ultimo_calculo, migrations.RunPython.noop),
    ]
